/**
 * Apply SQL migrations from ./drizzle (generated by `bun run db:generate`).
 * Usage: bun run db:migrate
 */
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";

const path = process.env.DATABASE_PATH ?? "./data/orders.sqlite";
mkdirSync(dirname(path), { recursive: true });

const sqlite = new Database(path);
const db = drizzle(sqlite);

await migrate(db, { migrationsFolder: "./drizzle" });
console.log("Migrations applied.");
